# Fase de construcción
FROM node:16 AS builder
WORKDIR /usr/share/app

# Instalar dependencias y construir la aplicación
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Fase de producción
FROM nginx:alpine
COPY --from=builder /usr/share/app/dist /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
